# Note : This is for development only, eventully the yml file(s) will be externalized in a git repository
spring:
  application:
    name: pdfeforms
  datasource:
    url: jdbc:postgresql://localhost/pdfeforms
    username: postgres
    password: pdfeforms
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

debug: false

logging:
  level:
    com.moj.digital.laa : DEBUG

